#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 NeoFOAM authors
#
# SPDX-License-Identifier: Unlicense

for v in FOAM_API WM_PROJECT WM_PROJECT_VERSION WM_PROJECT_DIR WM_ARCH_OPTION \
         WM_COMPILER_TYPE WM_COMPILER_LIB_ARCH WM_COMPILE_OPTION WM_LABEL_OPTION \
         WM_LABEL_SIZE WM_PRECISION_OPTION WM_MPLIB WM_ARCH WM_COMPILER WM_OPTIONS \
         WM_DIR WM_THIRD_PARTY_DIR FOAM_SRC FOAM_ETC FOAM_APP FOAM_SOLVERS \
         FOAM_UTILITIES FOAM_TUTORIALS FOAM_APPBIN FOAM_LIBBIN FOAM_SITE_APPBIN \
         FOAM_SITE_LIBBIN FOAM_USER_APPBIN FOAM_USER_LIBBIN FOAM_RUN FOAM_MPI \
         MPI_ARCH_PATH; do
    unset "${v}"
done
